django_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views
from dashboard.views import redirect_to_login

urlpatterns = [    
    path('account/', include('django.contrib.auth.urls')),    
    path('admin/', redirect_to_login, name='redirect_to_login'),
    path('login/', redirect_to_login, name='redirect_to_login'),    

    path('', include('news.urls')),    
    path('dashboard/', include('dashboard.urls')),    
    path('secret-admin/', admin.site.urls),   
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()    # jika sudah production url ini di gunakan, 
    # jangan lupa jalankan collectstatic

news/urls.py
from django.urls import path
from . import views

urlpatterns = [    
    path('', views.index, name='index'),
    path('detail/<slug:slug>/', views.detail, name='detail'),
    path('<str:kind>/list/<slug:slug>/', views.list, name='list'),

    path('tentang-kami/', views.about_us, name='about_us'),
    path('hubungi-kami/', views.contact_us, name='contact_us'),
    path('kirim-tulisan/', views.send_writing, name='send_writing'),

    #path('download-link/<uuid:pk>', views.download_link, name='download_link'),
    #path('redirect-link/<slug:slug>', views.redirect_link, name='redirect_link'),
    #path('set-inactive-link/<slug:slug>', views.set_inactive_link, name='set_inactive_link'),
    
]

news/models.py
import os
import uuid

from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import (GenericForeignKey,
                                                GenericRelation)
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.dispatch import receiver
from django.utils.text import slugify


class BaseModel(models.Model):
    # All model using di base model
    id = models.BigAutoField(primary_key=True, editable=False)
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 

    class Meta:
        app_label = 'news'
        abstract = True
        ordering = ['-created_at']        

class Photo(BaseModel):            
    # Image File Path
    file_path = models.ImageField()    

    # Generic relation from other model
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, blank=True)    
    object_id = models.PositiveIntegerField(blank=True)
    content_object = GenericForeignKey('content_type','object_id')

    def __str__(self):
        return self.file_path.url

class Logo(BaseModel):    
    name = models.CharField(max_length=100)
    photo = GenericRelation(Photo)    

    def __str__(self):
        return self.name       

class Categories(BaseModel):
    # News categories    
    name = models.CharField(max_length=50)   
    slug = models.SlugField(max_length=50, default='', unique=True, blank=True, editable=False)         

    def __str__(self):
        return self.name

    # untuk slug
    def save(self, *args, **kwargs):                
        self.slug = slugify(self.name)
        super(Categories, self).save(*args, **kwargs)

class StatusPublish(models.TextChoices):
    DRAFT = 'draft'
    PUBLISHED = 'published'

class StatusActive(models.TextChoices):
    NOT_ACTIVE = 'not active'
    ACTIVE = 'active'

class News(BaseModel):
    # judul berita
    title = models.CharField(max_length=500)    
    view_count = models.PositiveIntegerField(default=0, editable=False)         # jumlah views / read    
    
    # slug dari judul berita
    # mariaDB cannot create unique ID more than 255 char
    slug = models.SlugField(max_length=255, default='', unique=True, blank=True, editable=False)

    # gunakan ckeditor blank=True, null=True
    content = RichTextUploadingField()    

    # foreign key
    category = models.ForeignKey(Categories, on_delete=models.PROTECT)    
    admin = models.ForeignKey(User, on_delete=models.PROTECT, blank=True)
    photo = GenericRelation(Photo, related_query_name='news')  # relasi many2many
        
    # publish or draft
    status = models.CharField(max_length=20, choices=StatusPublish.choices, default=StatusPublish.PUBLISHED)    

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return '/%s/%s' % ( 'news', self.slug)         

    # untuk slug
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)        
        super(News, self).save(*args, **kwargs)

class Documents(BaseModel):
    file_path = models.FileField()    
    name = models.CharField(max_length=150)        
    size = models.BigIntegerField(null=True, blank=True, default=0, editable=False)                
    file_type = models.CharField(max_length=10, null=True, blank=True, default='', editable=False)               
    count = models.PositiveIntegerField(null=True, blank=True, default=0, editable=False)      
    status = models.CharField(max_length=20, choices=StatusPublish.choices, default=StatusPublish.PUBLISHED)      

    def __str__(self):
        return self.name

class DownloadLink(BaseModel):
    '''
        Data ini di generate saat ada permintaan download link
    '''
    documents = models.ForeignKey(Documents, on_delete=models.PROTECT)        
    # alamat lengkap
    # berisi url lengkap, sign key=key, salt=salt, max_age=3600) pwd = setting.secret_key 
    signature = models.TextField(null=True, blank=True)       # complete url after decoding

    # encrypt link
    enc_link = models.TextField(null=True, blank=True)       # complete url after decoding
    
    # aktif atau tidak
    status = models.CharField(max_length=20, choices=StatusActive.choices, default=StatusActive.ACTIVE)

    # url = models.URLField(max_length=500)       # complete url after decoding
    # expired = models.DateTimeField()          # already include in second
    # salt = models.CharField(max_length=200)   # simpan di signing
    # iv = models.CharField(max_length=200)     # simpan di signing as key
    # password 256bit = 32byte char
    # pwd = models.CharField(max_length=200)    # simpan di SETTINGS.SECRET_KEY

    # untuk mendeteksi user yg sama click download link yg sama
    ip = models.CharField(max_length=40, editable=False, db_index=True)
    # session = models.CharField(max_length=40, editable=False, db_index=True)
    # session berhubungan dengan login user, tidak digunakan di interface
    user_agent = models.CharField(max_length=255, editable=False)
    domain = models.CharField(max_length=255, editable=False, default='')

def save_embed_video(embed):
    '''
        Change from embed code to URL 
    '''
    jml = 0
    res = ''
    arr1 = embed.split(' ')
    found = False
    for i in arr1:
        if found:
            break
        arr2 = i.split('=')
        found = False
        for j in arr2:
            if (not found) and (j.lower()=='src'):
                found = True

            if found and (j.lower()!='src'):                
                if jml==0:
                    res += j     
                    jml += 1
                else:
                    res += '=' + j
                
                # print(res)               
                # self.embed_video = j.replace("\"","")
                # self.embed_video = self.embed_video.replace("&quot;","")                    
                #break
        
    if res.find('watch') <= 0:
        res = res.replace("\"","")
        res = res.replace("&quot;","")  
        
        # https://www.youtube.com/watch?v=AD8MaRZdOsY&amp;t=9s 
        # invalid embed
        return res       
    else:
        return None    

class Video(BaseModel):
    
    admin = models.ForeignKey(User, on_delete=models.PROTECT)    
    view_count = models.PositiveIntegerField(default=0, editable=False)         # jumlah views / read    
    
    title = models.CharField(max_length=500)
    embed = RichTextUploadingField(blank=True, null=True, config_name='embed_video') # , config_name='embed_video')        
    
    # ISI otomatis dari function save di bawah ini
    # field ini berguna untuk django-embed-video
    # ganti embed video supaya tidak perlu klik source dulu, bisa langsung paste dari embed youtube
    # embed_video = EmbedVideoField(blank=True, null=True)  # same like models.URLField()
    embed_video = models.URLField(blank=True, null=True)  # same like models.URLField()
    status = models.CharField(max_length=20, choices=StatusPublish.choices, default=StatusPublish.PUBLISHED)      

    # for save embed youtube
    photo = GenericRelation(Photo)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):                
        self.embed_video = save_embed_video(self.embed)

        # Download youtube thumbnail (PROHIBIT to UNSAVE content_objects) -- >> Move to views
        # video_id = get_video_id(self.embed_video)
        # file_path = download_thumbnail(exposed_request, video_id)
        # Photo.objects.create(content_object=self, file_path=file_path)    

        super(Video, self).save(*args, **kwargs)   

class PagesKind(models.TextChoices):
    ABOUT_US = 'about us'
    SEND_WRITING = 'send writing'
    CONTACT_US = 'contact us'

class Pages(BaseModel):        
    admin = models.ForeignKey(User, on_delete=models.PROTECT) # translatenya sama aja=admin juga

    view_count = models.PositiveIntegerField(default=0, editable=False)         # jumlah views / read
    share_count = models.PositiveIntegerField(default=0, editable=False)
    
    slug = models.SlugField(max_length=255, default='', unique=True, blank=True, editable=False)
    
    # site = models.ForeignKey(Site, on_delete=models.CASCADE)
    # admin = models.ForeignKey(User, on_delete=models.PROTECT)
    
    title = models.CharField(max_length=500)
    # slug = models.SlugField(max_length=255, default='', unique=True, blank=True),    
    # photo = GenericRelation(Photo)
    kind = models.CharField(max_length=20, choices=PagesKind.choices)    
    content = RichTextUploadingField(blank=True, null=True)

    def __str__(self):
        return self.title  

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)                        
        super(Pages, self).save(*args, **kwargs)    

class OptSocialMediaKinds(models.IntegerChoices):
    '''        
        Ubah jadi small Integer agar lebih hemat space database
    '''    
    FACEBOOK = 1, 'Facebook'
    TWITTER = 2, 'Twitter'
    PINTEREST = 3, 'Pinterest'
    YOUTUBE = 4, 'Youtube'
    INSTAGRAM = 5, 'Instagram'

class SocialMedia(BaseModel):    
    kind = models.SmallIntegerField(choices=OptSocialMediaKinds.choices)
    link =  models.URLField(max_length=255)
    # status = models.SmallIntegerField(choices=OptStatusPublish.choices, default=OptStatusPublish.PUBLISHED)
    status = models.CharField(max_length=20, choices=StatusPublish.choices, default=StatusPublish.PUBLISHED)    

    def __str__(self):
        #return {"%s %s"} % (self.jenis, self.site.name)
        return "{}".format(self.kind)

    # def save(self, *args, **kwargs):                
    #     super(SocialMedia, self).save(*args, **kwargs)  

# trigger         

@receiver(models.signals.post_delete, sender=Photo)

templates/news/snippets/footer-bottom.html
<div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="d-sm-flex justify-content-between align-items-center">
            <div class="fs-14 font-weight-600">
              © 2020 @ <a href="https://www.bootstrapdash.com/" target="_blank" class="text-white"> BootstrapDash</a>. All rights reserved.
            </div>
            <div class="fs-14 font-weight-600">
              Handcrafted by <a href="https://www.bootstrapdash.com/" target="_blank" class="text-white">BootstrapDash</a>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

templates/news/snippets/footer.html
{% load static %}
  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col-sm-5">
            {% for i in logo %}
                <a href="/"><img src="/media/{{i.foto}}" class="footer-logo" alt="" /></a>
            {% endfor %}
          <h5 class="font-weight-normal mt-4 mb-5">
            {% if about_us %}
                {{about_us.content|truncatewords_html:27|safe}} <a href="/tentang-kami/">selanjutnya</a>
            {% endif %}
          </h5>
          <ul class="social-media mb-3">
              {% for i in social_media %}
            <li>
              <a href="{{i.link}}">
                <i class="mdi mdi-{{i.get_kind_display|lower}}"></i>
              </a>
            </li>
                {% endfor %}
          </ul>
        </div>
        <div class="col-sm-4">
          <h3 class="font-weight-bold mb-3">RECENT POSTS</h3>
          
          {% for i in recent_posts %}
          <div class="row">
            <div class="col-sm-12">
              <div class="footer-border-bottom pb-2">
                <div class="row">
                  <div class="col-3">
                    <img
                      src="/media/{{i.foto}}"
                      alt="thumb"
                      class="img-fluid"
                    />
                  </div>
                  <div class="col-9">
                    <h5 class="font-weight-600">
                      <a href="/detail/{{i.slug}}/">{{i.title|truncatewords_html:7|safe}}</a>
                    </h5>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          {% endfor %}
          
        </div>
        <div class="col-sm-3">
          <h3 class="font-weight-bold mb-3">CATEGORIES</h3>
          {% for i in category_list %}
          <div class="footer-border-bottom pb-2">
            <div class="d-flex justify-content-between align-items-center">
              <h5 class="mb-0 font-weight-600"><a href="/news/list/{{i.slug}}/">{{i.name}}</a></h5>
              <!--<div class="count">1</div>-->
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

templates/news/snippets/navbar.html
{% load static %}

<header id="header">
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="navbar-top">
          <div class="d-flex justify-content-between align-items-center">
            <ul class="navbar-top-left-menu">
              <li class="nav-item">
                <a href="/tentang-kami/" class="nav-link">Tentang Kami</a>
              </li>
              <!-- <li class="nav-item">
                <a href="#" class="nav-link">Kegiatan</a>
              </li> -->
              <li class="nav-item">
                <a href="/kirim-tulisan/" class="nav-link">Kirim Tulisan</a>
              </li>              
            </ul>
            <ul class="navbar-top-right-menu">
              <li class="nav-item">
                <!-- <a href="#" class="nav-link"><i class="mdi mdi-magnify"></i></a> -->
              </li> 
              <li class="nav-item">
                <a href="/dashboard/" class="nav-link">Masuk</a>
              </li>
              <li class="nav-item">
                <a href="/hubungi-kami/" class="nav-link">Hubungi Kami</a>
              </li> 
            </ul>
          </div>
        </div>
        <div class="navbar-bottom">
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <a class="navbar-brand" href="/">
                
                {% for i in logo %}
                
                    <img src="/media/{{i.foto}}" alt=""/>
                {% endfor %}
                </a>
            </div>
            <div>
              <button
                class="navbar-toggler"
                type="button"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span class="navbar-toggler-icon"></span>
              </button>
              <div
                class="navbar-collapse justify-content-center collapse"
                id="navbarSupportedContent"
              >
                <ul
                  class="navbar-nav d-lg-flex justify-content-between align-items-center"
                >
                  <li>
                    <button class="navbar-close">
                      <i class="mdi mdi-close"></i>
                    </button>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="/">Beranda</a>
                  </li>

                  
                  {% for i in category %}

                    <li class="nav-item">
                      <a class="nav-link" href="/news/list/{{i.slug}}/">{{i.name}}</a>
                    </li>

                  {% endfor %}

                  <!-- <li class="nav-item">
                    <a class="nav-link" href="pages/business.html">Politik</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="pages/sports.html">Ekonomi</a>
                  </li> -->
                  <!-- <li class="nav-item">
                    <a class="nav-link" href="pages/art.html">Olah Raga</a>
                  </li> -->
                  <!--<li class="nav-item">
                    <a class="nav-link" href="#">Dokumen</a>
                  </li>                  -->
                  <!--<li class="nav-item">
                    <a class="nav-link" href="/hubungi-kami/">Hubungi Kami</a>
                  </li>-->
                </ul>
              </div>
            </div>
            <ul class="social-media">
                {% for i in social_media %}                
              <li>
                <a href="{{i.link}}" target="_BLANK">
                  <i class="mdi mdi-{{i.get_kind_display|lower}}"></i>
                </a>
              </li>
                {% endfor %}
              <!--<li>
                <a href="#">
                  <i class="mdi mdi-youtube"></i>
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="mdi mdi-twitter"></i>
                </a>
              </li> -->
            </ul>
          </div>
        </div>
      </nav>
    </div>
</header>

templates/news/snippets/script.html
{% load static %}
<!-- inject:js -->
<script src="{% static '/news/assets/vendors/js/vendor.bundle.base.js' %}"></script>
<!-- endinject -->
<!-- plugin js for this page -->
<script src="{% static '/news/assets/vendors/aos/dist/aos.js/aos.js' %}"></script>
<!-- End plugin js for this page -->
<!-- Custom js for this page-->
<script src="{% static '/news/assets/js/demo.js' %}"></script>
<script src="{% static '/news/assets/js/jquery.easeScroll.js' %}"></script>
<!-- End custom js for this page-->

templates/news/snippets/style.html
{% load static %}
<link
rel="stylesheet"
href="{% static '/news/assets/vendors/mdi/css/materialdesignicons.min.css' %}"
/>
<link rel="stylesheet" href="{% static '/news/assets/vendors/aos/dist/aos.css/aos.css' %}" />

<!-- End plugin css for this page -->
<link rel="shortcut icon" href="{% static '/news/assets/images/favicon.png' %}" />

<!-- inject:css -->
<link rel="stylesheet" href="{% static '/news/assets/css/style.css' %}">
<!-- endinject -->

<style>
    .footer-top a {
        color: white;
    }

    a {
        color: white;
    }

    a:hover {
        color: burlywood;
        text-decoration: none;
    }

    p > a {
        color: grey;
    }

    h5 > a {
        color: grey;
    }

    h2 > a {
        color: grey;
    }

    .content-wrapper {
        padding: 30px 0;
    }
    
    .aboutus-wrapper {
        padding: 0 30px;
    }
</style>